apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shell
  name: shell
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: nicolaka/netshoot
    imagePullPolicy: Always
    name: shell